# Generated by Django 5.2.6 on 2025-09-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField()),
                ('customer_name', models.TextField()),
                ('product_name', models.TextField(choices=[('Wood', 'Wood'), ('Furniture', 'Furniture')])),
                ('product_type', models.TextField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('payment_type', models.TextField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank Overdraft', 'Bank Overdraft')])),
                ('sales_agent', models.TextField(max_length=10)),
                ('transport_required', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField()),
                ('date', models.DateField()),
                ('product_name', models.TextField(choices=[('Timber', 'Timber'), ('Sofa', 'Sofa'), ('Tables', 'Tables'), ('Cupboards', 'Cupboards'), ('Drawer', 'Drawer'), ('Poles', 'Poles')])),
                ('product_type', models.TextField()),
                ('quantity', models.IntegerField()),
                ('supplier_name', models.TextField()),
                ('cost', models.CharField()),
                ('price', models.CharField()),
                ('origin', models.TextField()),
            ],
        ),
    ]
