# Generated by Django 5.2.5 on 2025-09-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_populate_product_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
