# Generated by Django 5.2.5 on 2025-09-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_sale_product_id_alter_stock_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='transport_required',
            field=models.BooleanField(default=False),
        ),
    ]
