# Generated by Django 5.2.5 on 2025-09-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_sale_transport_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product_name',
            field=models.TextField(choices=[('Timber', 'Timber'), ('Sofa', 'Sofa'), ('Tables', 'Tables'), ('Cupboards', 'Cupboards'), ('Drawer', 'Drawer'), ('Poles', 'Poles')]),
        ),
    ]
