# Generated by Django 5.2.5 on 2025-09-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_sale_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_type',
            field=models.CharField(choices=[('Wood', 'Wood'), ('Furniture', 'Furniture')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='origin',
            field=models.CharField(choices=[('Western', 'Western'), ('Central', 'Central'), ('Eastern', 'Eastern')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_type',
            field=models.CharField(choices=[('Wood', 'Wood'), ('Furniture', 'Furniture')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='supplier_name',
            field=models.CharField(max_length=100),
        ),
    ]
