# Generated by Django 5.2.5 on 2025-09-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_sale_customer_name_alter_sale_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sales_agent',
            field=models.CharField(max_length=50),
        ),
    ]
