# Generated by Django 5.2.5 on 2025-09-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_sale_sales_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Timber', 'Timber'), ('Sofa', 'Sofa'), ('Tables', 'Tables'), ('Cupboards', 'Cupboards'), ('Drawer', 'Drawer'), ('Poles', 'Poles')], max_length=50)),
                ('product_type', models.CharField(choices=[('Wood', 'Wood'), ('Furniture', 'Furniture')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional product description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'product_type'],
                'unique_together': {('name', 'product_type')},
            },
        ),
    ]
