# Generated by Django 5.2.5 on 2025-09-30 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='product_ref',
            field=models.ForeignKey(blank=True, help_text='Select product from catalog', null=True, on_delete=django.db.models.deletion.PROTECT, to='home.product'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product_ref',
            field=models.ForeignKey(blank=True, help_text='Select product from catalog', null=True, on_delete=django.db.models.deletion.PROTECT, to='home.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_name',
            field=models.TextField(blank=True, choices=[('Timber', 'Timber'), ('Sofa', 'Sofa'), ('Tables', 'Tables'), ('Cupboards', 'Cupboards'), ('Drawer', 'Drawer'), ('Poles', 'Poles')], null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_type',
            field=models.CharField(blank=True, choices=[('Wood', 'Wood'), ('Furniture', 'Furniture')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_name',
            field=models.TextField(blank=True, choices=[('Timber', 'Timber'), ('Sofa', 'Sofa'), ('Tables', 'Tables'), ('Cupboards', 'Cupboards'), ('Drawer', 'Drawer'), ('Poles', 'Poles')], null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_type',
            field=models.CharField(blank=True, choices=[('Wood', 'Wood'), ('Furniture', 'Furniture')], max_length=20, null=True),
        ),
    ]
