# Generated by Django 5.2.6 on 2025-10-01 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product_name',
            field=models.CharField(choices=[('Timber', 'Timber'), ('Sofa', 'Sofa'), ('Tables', 'Tables'), ('Cupboards', 'Cupboards'), ('Drawer', 'Drawer'), ('Poles', 'Poles')], default='Timber', help_text='Select the product category', max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_ref',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from product details', null=True, on_delete=django.db.models.deletion.PROTECT, to='home.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_type',
            field=models.CharField(choices=[('Wood', 'Wood'), ('Furniture', 'Furniture')], default='Furniture', help_text='Select the product type', max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_name',
            field=models.CharField(choices=[('Timber', 'Timber'), ('Sofa', 'Sofa'), ('Tables', 'Tables'), ('Cupboards', 'Cupboards'), ('Drawer', 'Drawer'), ('Poles', 'Poles')], default='Timber', help_text='Select the product category', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_ref',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from product details', null=True, on_delete=django.db.models.deletion.PROTECT, to='home.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_type',
            field=models.CharField(choices=[('Wood', 'Wood'), ('Furniture', 'Furniture')], default='Furniture', help_text='Select the product type', max_length=20),
        ),
    ]
