# Generated by Django 5.2.5 on 2025-10-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_sale_product_name_alter_sale_product_ref_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
