# Generated by Django 5.2.5 on 2025-10-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20251001_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_sales_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Automatically calculated from quantity × unit price', max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per unit in dollars', max_digits=10),
        ),
    ]
