# Generated by Django 5.2.5 on 2025-10-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_sale_total_sales_amount_sale_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Automatically calculated from quantity × unit cost', max_digits=12),
        ),
        migrations.AddField(
            model_name='stock',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per unit item in dollars', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cost',
            field=models.CharField(help_text='Legacy field - will be removed in future versions'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.CharField(help_text='Unit selling price - legacy field'),
        ),
    ]
