# Generated by Django 5.2.5 on 2025-10-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_stock_total_cost_stock_unit_cost_alter_stock_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='cost',
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.CharField(help_text='Unit selling price'),
        ),
    ]
