# Generated by Django 5.2.5 on 2025-10-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_stock_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='supplier_name',
            field=models.CharField(choices=[('Mbawo Timberworks', 'Mbawo Timberworks'), ('Rosewood Timbers', 'Rosewood Timbers'), ('Muto Timber Suppliers', 'Muto Timber Suppliers'), ('Matongo WoodWorks', 'Matongo WoodWorks')], max_length=100),
        ),
    ]
