# Generated by Django 5.2.5 on 2025-10-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_stock_supplier_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer full name', max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Customer phone number', max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Customer email address', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Customer physical address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Supplier company name', max_length=100, unique=True)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person', max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Supplier phone number', max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Supplier email address', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Supplier physical address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
