# Generated by Django 5.2.5 on 2025-10-11 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_customer_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='supplier_name',
        ),
        migrations.AddField(
            model_name='stock',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Select the supplier who provided this product', null=True, on_delete=django.db.models.deletion.PROTECT, to='home.supplier'),
        ),
    ]
