# Generated by Django 5.2.5 on 2025-10-11 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_stock_supplier_name_stock_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Select the customer for this sale', null=True, on_delete=django.db.models.deletion.PROTECT, to='home.customer'),
        ),
    ]
