# Generated by Django 5.2.5 on 2025-10-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_sale_customer_name_sale_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(help_text='Customer physical address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(help_text='Customer email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='Customer phone number', max_length=15),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(help_text='Supplier physical address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(help_text='Primary contact person', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(help_text='Supplier email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(help_text='Supplier phone number', max_length=15),
        ),
    ]
